"""build_table.py -- render level_atlas.csv into the table markup for index.html.

The page must not carry hand-typed numbers. They would be a second copy of the CSV, free to
drift from it, and the whole argument of the page is that a figure should be traceable to
the values behind it.

    python atlas/build_table.py > atlas/_table.html

and paste the result between the markers in index.html, or run with --write to do it.
"""
from __future__ import annotations

import argparse
import csv
import html
from pathlib import Path

HERE = Path(__file__).parent

# display order and headings; keys match the "measure" column of the CSV
GROUPS = [
    ("h_ant",    "Vertebral body height, ventral", "mm"),
    ("h_post",   "Vertebral body height, dorsal", "mm"),
    ("endplate", "Superior endplate width", "mm"),
    ("canal_w",  "Spinal canal width", "mm"),
    ("canal_ap", "Spinal canal depth (AP)", "mm"),
    ("pedicle",  "Transverse pedicle width", "mm"),
    ("disc",     "Disc height", "mm"),
    ("hu",       "Trabecular attenuation", "HU"),
]
PRETTY_DISC = {"L1L2": "L1–L2", "L2L3": "L2–L3", "L3L4": "L3–L4",
               "L4L5": "L4–L5", "L5S1": "L5–S1"}


def rows():
    with open(HERE / "level_atlas.csv", encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def build() -> str:
    data = rows()
    out = []
    for key, title, unit in GROUPS:
        sel = [r for r in data if r["measure"] == key]
        if not sel:
            continue
        out.append(f'<h3 class="atlas__mname">{html.escape(title)} '
                   f'<span class="atlas__unit">({unit})</span></h3>')
        out.append('<div class="atlas__scroll"><table class="atlas__table">')
        out.append("<thead><tr><th>Level</th><th>n</th><th>Median</th>"
                   "<th>IQR</th><th>5th–95th</th><th>Mean ± SD</th></tr></thead><tbody>")
        for r in sel:
            lv = PRETTY_DISC.get(r["level"], r["level"])
            out.append(
                f'<tr><th scope="row">{lv}</th><td>{r["n"]}</td>'
                f'<td>{r["median"]}</td>'
                f'<td>{r["q1"]}&ndash;{r["q3"]}</td>'
                f'<td>{r["p5"]}&ndash;{r["p95"]}</td>'
                f'<td>{r["mean"]} &plusmn; {r["sd"]}</td></tr>')
        out.append("</tbody></table></div>")
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true",
                    help="splice into index.html between the generated-table markers")
    a = ap.parse_args()
    table = build()
    if not a.write:
        print(table)
        return
    p = HERE / "index.html"
    s = p.read_text(encoding="utf-8")
    A = "<!-- TABLE:BEGIN generated by build_table.py -- do not hand-edit -->"
    B = "<!-- TABLE:END -->"
    i, j = s.index(A) + len(A), s.index(B)
    p.write_text(s[:i] + "\n" + table + "\n" + s[j:], encoding="utf-8")
    n = table.count("<tr><th scope")
    print(f"wrote {n} rows into index.html")


if __name__ == "__main__":
    main()
